#!/bin/bash
set -e

FREQ="59" # Hz

mkdir -p data
mstat -o data/mem-glibc.tsv                                           -freq $FREQ -- ./fragmenter
mstat -o data/mem-tcmalloc.tsv -env LD_PRELOAD=libtcmalloc_minimal.so -freq $FREQ -- ./fragmenter
mstat -o data/mem-mesh.tsv     -env LD_PRELOAD=libmesh.so             -freq $FREQ -- ./fragmenter

R --vanilla <./stat.r
