# To build use:
# docker build -t bpowers/spec:mesh-v2 .
FROM bpowers/spec:mesh
MAINTAINER Bobby Powers <bpowers@cs.umass.edu>

LABEL description="SPEC w/ mesh"

COPY ./libmesh.so /usr/local/lib/
COPY ./mstat /usr/local/bin
